@a11yui/angular:
  - packages/angular/*
  - packages/angular/**/*
  
@a11yui/core:
  - packages/core/*
  - packages/core/**/*

@a11yui/react:
  - packages/react/*
  - packages/react/**/*

@a11yui/svelte:
  - packages/svelte/*
  - packages/svelte/**/*

@a11yui/vue:
  - packages/vue/*
  - packages/vue/**/*

@a11yui/web-components:
  - packages/web-components/*
  - packages/web-components/**/*

@a11yui/wordpress-plugin:
  - packages/wordpress-plugin/*
  - packages/wordpress-plugin/**/*

@shared/utils:
  - shared/utils/*
  - shared/utils/**/*

documentation:
  - docs/*
  - docs/**/*
