env:
  browser: true
  es2021: true
  # node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
    - usePrettierrc: true
  indent:
    - off
  linebreak-style:
    - error
    - unix
  max-len:
    - warn
    - code: 80
      ignoreComments: true
  quotes:
    - error
    - single
  semi:
    - error
    - always
